mode: train
model_name: dla60x
data_dir: /home/grads/z/zshuying/dl_resnet/cifar-10-batches-py
save_dir: /home/grads/z/zshuying/DL_project/ckpts


levels: [1, 1, 1, 3, 4, 1]
residual_root: True,
channels: [16, 32, 128, 256, 512, 1024]
block: BottleneckX
num_classes: 10

lr: 0.1
max_epoch: 500
weight_decay: 0.0001
step_ratio: 0.1
lr_adjust: step
batch_size: 256
save_interval: 10
