mode: train
model_name: dla46v2
data_dir: /home/grads/z/zshuying/dl_resnet/cifar-10-batches-py
save_dir: /home/grads/z/zshuying/DL_project/ckpts


levels: [1, 1, 1, 2, 2, 1]
                
channels: [16, 32, 64, 64, 128, 256]
block: Bottleneck
num_classes: 10

lr: 0.001
max_epoch: 500
weight_decay: 0.0001
step_ratio: 0.1
lr_adjust: step
batch_size: 350
save_interval: 10