mode: predict
model_name: simpleDLA
data_dir: /home/grads/z/zshuying/shuying_zhu/private_test_images_2024.npy
save_dir: /home/grads/z/zshuying/shuying_zhu/saved_models
ckpt: /home/grads/z/zshuying/shuying_zhu/saved_models/simpleDLA-118-0.93.ckpt
result_dir: /home/grads/z/zshuying/shuying_zhu/predictions.npy
num_classes: 10

lr: 0.1
max_epoch: 200
weight_decay: 0.0005
step_ratio: 0.1
lr_adjust: step
batch_size: 128
save_interval: 10