mode: train
model_name: simpleDLA
data_dir: /home/grads/z/zshuying/dl_resnet/cifar-10-batches-py
save_dir: /home/grads/z/zshuying/shuying_zhu/saved_models


num_classes: 10

lr: 0.1
max_epoch: 200
weight_decay: 0.0005
step_ratio: 0.1
lr_adjust: step
batch_size: 128
save_interval: 10